package com.github.StasMalykhin.aviabot.entity.enums;

/**
 * @author Stanislav Malykhin
 */
public enum UserState {
    SEARCH_CITIES_WITH_AIRPORT,
    SEARCH_AIR_TICKETS,
    ENTER_DEPARTURE_CITY_NAME_WHEN_SEARCHING_FOR_AIR_TICKETS,
    ENTER_DESTINATION_CITY_NAME_WHEN_SEARCHING_FOR_AIR_TICKETS,
    ENTER_DEPARTURE_DATE_WHEN_SEARCHING_FOR_AIR_TICKETS,
    SHOW_SUBSCRIPTIONS,
    START
}
